name: marp-github-actions
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install jq
      - run: |
          directory=$(cat config.json | jq -r .directory)
          output_format=$(cat config.json | jq -r .output_format)
          echo "DIR=${directory}" >> $GITHUB_OUTPUT
          echo "FORMAT=${output_format}" >> $GITHUB_OUTPUT
        id: config
      - run: mkdir -p dist && chmod 777 dist
      - run: docker run --rm --init -v "$(pwd):/home/marp/app/"
              -e LANG="ja_JP.UTF-8" marpteam/marp-cli ${{steps.config.outputs.DIR}}/slide.md
              --${{steps.config.outputs.FORMAT}}
              -o dist/output_slide.${{steps.config.outputs.FORMAT}}
              --allow-local-files
      - name: Rename HTML file to index.html for GitHub Pages
        if: steps.config.outputs.FORMAT == 'html'
        run: mv dist/output_slide.html dist/index.html
      - name: Upload artifact for download
        uses: actions/upload-artifact@v4
        with:
          name: output_slide
          path: dist/
      - name: Upload artifact for GitHub Pages
        if: steps.config.outputs.FORMAT == 'html'
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
